### ISSUE TITLE
The Cache class may create deadlocks

### ISSUE THREAD

**Issue by fsoikin** [ninject/Ninject#124] opened 2014-04-05 01:36 UTC
The `Cache` class calls its `Forget` method inside `lock( this.entries )` (in particular, [here](https://github.com/ninject/ninject/blob/master/src/Ninject/Activation/Caching/Cache.cs#L160), [here](https://github.com/ninject/ninject/blob/master/src/Ninject/Activation/Caching/Cache.cs#L181), [here](https://github.com/ninject/ninject/blob/master/src/Ninject/Activation/Caching/Cache.cs#L199), and [here](https://github.com/ninject/ninject/blob/master/src/Ninject/Activation/Caching/Cache.cs#L211)), which in turn [calls Pipeline.Deactivate](https://github.com/ninject/ninject/blob/master/src/Ninject/Activation/Caching/Cache.cs#L254) - potentially external code.

Calling code you don't control from within a synchronization block is major no-no, thread-safely speaking. This may (and does, in my case) lead to deadlocks.

**Comment by bnordli** [comment] 2015-02-04 15:06
Any update on this? We have stumbled over the exact same problem:

Basically, we have a PerRequest object to hold database sessions, and use the OnePerRequestHttpModule to commit transactions when the request has ended. We soon found out that in the Dispose method of this object, the thread holds the cache lock so we have to make sure not to call into Ninject again.

A suggested fix would be for Forget to return a list of forgotten objects, for the callers to deactivate them outside of the lock.

**Comment by zapalap** [comment] 2018-01-02 22:25
I actually have encountered a deadlock in production caused by this exact behavior. 

We are using Ninject to provide per-request instances of [System.Net.Mail.SmtpClient](https://msdn.microsoft.com/en-us/library/system.net.mail.smtpclient(v=vs.110).aspx). Turns out, that when disposing, SmtpClient sends an SMTP QUIT message through a socket and awaits server response without any timeout. If that data never arrives, the lock on entries is never released and the application hangs.

**Comment by drieseng** [comment] 2019-03-23 08:31
Duplicate of #182.

**Closed by drieseng** 2019-03-23 08:31 UTC
